language: node_js
node_js:
    - "10"

addons:
    sonarcloud:
        organization: "criatecnologiainovacao"
        token:
            secure: $SONAR_TOKEN

env:
    - TRAVIS_CI=1

git:
    depth: false

cache:
    npm: true
    directories:
        - node_modules

install:
    npm i

script:
    - npm run lint
    - npm run build
    - npm test
    - eslint -f json -o report.json src
    - sonar-scanner